name: "📌 New Issue Ticket"
description: "Submit a new issue with predefined categories"
title: "[New Issue] <Add Title Here>"
labels: ["triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "### 📝 Please select the type of issue"

  - type: dropdown
    id: category1
    attributes:
      label: "🔹 Select Primary Issue Category"
      description: "Choose the most relevant category for this issue"
      options:
        - BGC
        - Core
        - Deep
        - GDAC
        - General queries
        - GTS
        - Hex file
        - Json
        - Meta file
        - Missing data/file
        - NCEI
        - Phy file
        - Polar
        - QC
        - Reprocess request
        - Ticketing queries
        - Trajectory file
    validations:
      required: true

  - type: dropdown
    id: category2
    attributes:
      label: "🔹 Select Secondary Issue Category (Optional)"
      description: "Choose an additional category if applicable"
      options:  
        - No Additional Category
        - BGC
        - Core
        - Deep
        - GDAC
        - General queries
        - GTS
        - Hex file
        - Json
        - Meta file
        - Missing data/file
        - NCEI
        - Phy file
        - Polar
        - QC
        - Reprocess request
        - Ticketing queries
        - Trajectory file

  - type: dropdown
    id: organization
    attributes:
      label: "🏢 Select Organization"
      description: "Choose the organization submitting this issue"
      options:
        - AOML
        - Coriolis
        - FSU
        - iFremer
        - JPL
        - MBARI
        - MIT
        - Navoceano
        - NAVO
        - NCEI
        - NDBC
        - Other International
        - Other National
        - PMEL
        - SIO
        - UH
        - UMaine
        - UW
        - WHOI
    validations:
      required: true

  - type: input
    id: wmo_float_id
    attributes:
      label: "🌊 WMO Float ID# (Optional)"
      description: "Enter the WMO Float ID# if applicable."
      placeholder: "e.g., 1234567"
    validations:
      required: false

  - type: input
    id: cycle_number
    attributes:
      label: "🔄 Cycle # (Optional)"
      description: "Enter the Cycle # if applicable."
      placeholder: "e.g., 25"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "📝 Detailed Description"
      description: "Provide additional details about this issue."
      placeholder: "Explain the issue here..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🚦 Set Priority (1 = Highest, 6 = Lowest)"
      description: "Select the priority level for this issue."
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6" 
    validations:
      required: true

  - type: checkboxes
    id: confirm
    attributes:
      label: "✅ Confirmation"
      description: "Check the box to confirm before submission."
      options:
        - label: "I have reviewed all details before submitting."
          required: true
