name: "📌 New Issue Ticket"
description: "Submit a new issue with predefined categories"
title: "[New Issue] <Add Title Here>"
labels: ["triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "### 📝 Please select the type of issue"

  - type: dropdown
    id: category
    attributes:
      label: "🔹 Select Issue Category"
      description: "Choose the most relevant category for this issue"
      options:
        - Reprocess request
        - QC queries
        - Phy file queries
        - Hex file queries
        - Meta files queries
        - Traj file queries
        - GDAC queries
        - GTS queries
        - NCEI queries
        - General queries
        - PI queries
        - Core queries
        - Deep queries
        - BGC queries
        - Polar queries
    validations:
      required: true

  - type: dropdown
    id: organization
    attributes:
      label: "🏢 Select Organization"
      description: "Choose the organization submitting this issue"
      options:
        - AOML
        - SIO
        - UW
        - WHOI
        - PMEL
        - NAVO
        - UH
        - MIT
        - JPL
        - NDBC
        - FSU
        - Navoceano
        - UMaine
        - iFremer
        - Coriolis
        - NCEI
        - Other National
        - Other International
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 Detailed Description"
      description: "Provide additional details about this issue."
      placeholder: "Explain the issue here..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🚦 Set Priority (1 = Highest, 6 = Lowest)"
      description: "Select the priority level for this issue."
      options:
        - "1 - Critical"
        - "2 - High"
        - "3 - Medium High"
        - "4 - Medium"
        - "5 - Low"
        - "6 - Very Low"
    validations:
      required: true

  - type: checkboxes
    id: confirm
    attributes:
      label: "✅ Confirmation"
      description: "Check the box to confirm before submission."
      options:
        - label: "I have reviewed all details before submitting."
          required: true
