name: "📌 New Issue Ticket"
description: "Submit a new issue with predefined categories"
title: "[New Issue] <Add Title Here>"
labels: ["triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "### 📝 Please select the type of issue"

  - type: checkboxes  # ✅ Changed from dropdown to checkboxes
    id: category
    attributes:
      label: "🔹 Select Issue Category"
      description: "Choose all applicable categories for this issue"
      options:
        - label: "Reprocess request"
        - label: "QC queries"
        - label: "Phy file queries"
        - label: "Hex file queries"
        - label: "Meta files queries"
        - label: "Traj file queries"
        - label: "GDAC queries"
        - label: "GTS queries"
        - label: "NCEI queries"
        - label: "General queries"
        - label: "PI queries"
        - label: "Core queries"
        - label: "Deep queries"
        - label: "BGC queries"
        - label: "Polar queries"
        - label: "Ticketing queries"
    validations:
      required: true  # ✅ Ensures at least one category is selected

  - type: dropdown
    id: organization
    attributes:
      label: "🏢 Select Organization"
      description: "Choose the organization submitting this issue"
      options:
        - AOML
        - SIO
        - MBARI
        - UW
        - WHOI
        - PMEL
        - NAVO
        - UH
        - MIT
        - JPL
        - NDBC
        - FSU
        - Navoceano
        - UMaine
        - iFremer
        - Coriolis
        - NCEI
        - Other National
        - Other International
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 Detailed Description"
      description: "Provide additional details about this issue."
      placeholder: "Explain the issue here..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🚦 Set Priority (1 = Highest, 6 = Lowest)"
      description: "Select the priority level for this issue."
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6" 
    validations:
      required: true

  - type: checkboxes
    id: confirm
    attributes:
      label: "✅ Confirmation"
      description: "Check the box to confirm before submission."
      options:
        - label: "I have reviewed all details before submitting."
          required: true
