name: Auto-Label Issues with Private Repo Reference

on:
  issues:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Private Repo Issue Label
        env:
          GH_TOKEN: ${{ secrets.PAT_SECRET }}
          PUBLIC_ISSUE_NUMBER: ${{ github.event.issue.number }}
          PRIVATE_REPO: "TicketTesting77/aoml-internal-tracking"

        run: |
          echo "🔍 Searching for the corresponding issue in $PRIVATE_REPO"

          # Search for an open issue with the same title in the private repo
          SEARCH_RESULTS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/search/issues?q=${{ github.event.issue.title }}+repo:$PRIVATE_REPO&type=issues")

          # Extract the first matching private issue number
          PRIVATE_ISSUE_NUMBER=$(echo "$SEARCH_RESULTS" | jq '.items[0].number')

          if [[ "$PRIVATE_ISSUE_NUMBER" == "null" || -z "$PRIVATE_ISSUE_NUMBER" ]]; then
            echo "❌ No matching private issue found. Exiting."
            exit 0
          fi

          echo "✅ Found private issue #$PRIVATE_ISSUE_NUMBER. Adding label to public issue."

          # Assign a label based on the private repo issue number
          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"labels\": [\"private-issue-$PRIVATE_ISSUE_NUMBER\"]}" \
            "https://api.github.com/repos/TicketTesting77/aoml-ticket-pub/issues/$PUBLIC_ISSUE_NUMBER/labels"

          echo "✅ Label private-issue-$PRIVATE_ISSUE_NUMBER added successfully."
