name: Auto-Response to Issue Submissions

on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Post Acknowledgement Comment
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT_SECRET }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"body": "✅ Thank you for submitting your request! Our team has received it and will review it shortly."}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
