name: Auto-Response to Issue Submissions

on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Post Acknowledgement
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_SECRET }}
          script: |
            const { context, github } = require('@actions/github');
            
            const issueNumber = context.payload.issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            console.log(`Adding a comment to issue #${issueNumber} in ${repoOwner}/${repoName}`);

            await github.rest.issues.createComment({
              owner: repoOwner,
              repo: repoName,
              issue_number: issueNumber,
              body: "✅ Thank you for submitting your request! Our team has received it and will review it shortly."
            });

            console.log("Comment added successfully.");
